# Generated by Django 5.0.2 on 2024-02-21 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_post_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_content', models.CharField(max_length=500)),
                ('reply_writer', models.CharField(max_length=50)),
                ('reply_number', models.IntegerField(default=0)),
                ('reply_sink', models.IntegerField(default=0)),
                ('reply_secret', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.post')),
            ],
            options={
                'db_table': 'tbl_reply',
                'ordering': ['-id'],
            },
        ),
    ]
