# Generated by Django 5.0.2 on 2024-02-21 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_status'),
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_number',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_secret',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_sink',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_writer',
        ),
        migrations.AddField(
            model_name='reply',
            name='group_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_depth',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_private_status',
            field=models.BooleanField(choices=[(True, '비밀 댓글'), (False, '일반 댓글')], default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='member.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(),
        ),
    ]
