# Generated by Django 5.0.2 on 2024-02-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_remove_reply_reply_number_remove_reply_reply_secret_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='reply',
            name='group_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
