# Generated by Django 5.0.2 on 2024-02-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.BigIntegerField(default=1)),
                ('product_name', models.CharField(max_length=3000)),
                ('product_price', models.BigIntegerField(default=0)),
                ('product_count', models.BigIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_product',
                'ordering': ['-id'],
            },
        ),
    ]
