# Generated by Django 5.0.2 on 2024-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='member',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
